# Generated by Django 5.2.17 on 2026-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(help_text='Auto-generated unique ID. Format: TG-XXXXXXX', max_length=20, unique=True)),
                ('common_name', models.CharField(help_text="Common/local name of the tree, e.g. 'Neem', 'Banyan'.", max_length=200)),
                ('scientific_name', models.CharField(blank=True, default='', help_text="Scientific (Latin) name, e.g. 'Azadirachta indica'.", max_length=300)),
                ('location_name', models.CharField(help_text="Human-readable location, e.g. 'Ahmedabad, Gujarat'.", max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude of the tree.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude of the tree.', max_digits=9, null=True)),
                ('estimated_age_years', models.PositiveIntegerField(blank=True, help_text='Estimated age of the tree in years.', null=True)),
                ('planting_date', models.DateField(blank=True, help_text='Date the tree was planted, if known.', null=True)),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Current measured height in metres.', max_digits=6, null=True)),
                ('trunk_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Trunk circumference at chest height, in centimetres.', max_digits=7, null=True)),
                ('native_status', models.CharField(choices=[('NATIVE', 'Native'), ('INTRODUCED', 'Introduced'), ('NATURALISED', 'Naturalised'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('sunlight_requirement', models.CharField(blank=True, choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SUN', 'Partial Sun / Shade'), ('FULL_SHADE', 'Full Shade')], default='FULL_SUN', max_length=20)),
                ('water_requirement', models.CharField(blank=True, choices=[('LOW', 'Low — drought-tolerant'), ('MEDIUM', 'Medium — regular watering'), ('HIGH', 'High — frequent watering')], default='MEDIUM', max_length=10)),
                ('suitable_climate', models.CharField(blank=True, default='', help_text='Climate zones this species thrives in.', max_length=200)),
                ('soil_requirement', models.TextField(blank=True, default='', help_text='Soil type and quality this species prefers.')),
                ('expected_growth', models.TextField(blank=True, default='', help_text='Expected growth rate and mature size.')),
                ('environmental_benefits', models.TextField(blank=True, default='', help_text='Carbon sequestration, air quality, shade, etc.')),
                ('wildlife_supported', models.TextField(blank=True, default='', help_text='Birds, insects, or mammals that benefit from this tree.')),
                ('additional_notes', models.TextField(blank=True, default='', help_text='Any extra notes about this specific tree.')),
                ('health_status', models.CharField(choices=[('HEALTHY', '🟢 Healthy'), ('NEEDS_ATTENTION', '🟡 Needs Attention'), ('AT_RISK', '🔴 At Risk'), ('EMERGENCY', '🚨 Emergency'), ('LOST', '💀 Lost / Removed'), ('UNKNOWN', '❓ Unknown')], default='HEALTHY', help_text='Current health condition of the tree.', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, help_text="When was the tree's health last verified by a guardian?", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if the tree has been removed from the active registry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'ordering': ['-created_at'],
            },
        ),
    ]
