# Generated by Django 5.2.17 on 2026-09-12 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='The user who first registered this tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
